name: gate
on: [push, pull_request]

jobs:
  gate:
    name: Gate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: bash <(wget -qO- https://github.com/MATF-Software-Verification/VS-project-ci/blob/main/gate)
  
